server:
  port: 8080
  servlet:
    context-path: /internetBookShop
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/internet_book_shop?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3.1415926
  thymeleaf:
    cache: false
    prefix: classpath:static/
    suffix: .html
        
mybatis:
  config-location: classpath:sqlMapConfig.xml
  mapper-locations: classpath:sqlMap/**.xml
  

